# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Programming Engineer Website'
copyright = '2023, Jeroen de Vries'
author = 'Jeroen de Vries'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    "myst_parser",
    'sphinx_sitemap',
    'sphinx.ext.intersphinx',
    ]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'README.md']



# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "furo"
html_title = "Programming Engineer"
html_baseurl = "https://www.programming-engineer.nl"
html_static_path = ['_static']
html_theme_options = {
    "light_logo": "logo.png",
    "dark_logo": "logo.png",
}

# -- Language options ----------------------
# https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#internationalization
# https://www.sphinx-doc.org/en/master/usage/advanced/intl.html#translating-with-sphinx-intl

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'
locale_dirs = ['locale/']   # path is example but recommended.mak
gettext_compact = False     # optional.
